# Generated by Django 6.0.4 on 2026-05-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0002_bajassig_empleadoscompletossig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pos_actual', models.CharField(blank=True, db_column='Nº Pos Actual', max_length=255, null=True)),
                ('f_efva', models.CharField(blank=True, db_column='F Efva', max_length=255, null=True)),
                ('estado_psn', models.CharField(blank=True, db_column='Estado Psn', max_length=255, null=True)),
                ('fecha_captura', models.CharField(blank=True, db_column='Fecha Captura', max_length=255, null=True)),
                ('cd_motivo', models.CharField(blank=True, db_column='Cd Motivo', max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, db_column='Motivo', max_length=255, null=True)),
                ('cd_un', models.CharField(blank=True, db_column='Cd UN', max_length=255, null=True)),
                ('unidad_de_negocio', models.CharField(blank=True, db_column='Unidad de Negocio', max_length=255, null=True)),
                ('unidad_adva', models.CharField(blank=True, db_column='Unidad Adva#', max_length=255, null=True)),
                ('cd_departamento', models.CharField(blank=True, db_column='Cd Departamento', max_length=255, null=True)),
                ('cd_puesto', models.CharField(blank=True, db_column='Cd Puesto', max_length=255, null=True)),
                ('estado_ptal', models.CharField(blank=True, db_column='Estado Ptal', max_length=255, null=True)),
                ('fecha_est', models.CharField(blank=True, db_column='Fecha Est', max_length=255, null=True)),
                ('maximo', models.CharField(blank=True, db_column='Máximo', max_length=255, null=True)),
                ('depnd_drt', models.CharField(blank=True, db_column='Depnd Drt', max_length=255, null=True)),
                ('depnd_indrt', models.CharField(blank=True, db_column='Depnd Indrt', max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicación', max_length=255, null=True)),
                ('nvl_direc', models.CharField(blank=True, db_column='Nvl Direc', max_length=255, null=True)),
                ('plan_sal', models.CharField(blank=True, db_column='Plan Sal', max_length=255, null=True)),
                ('grado', models.CharField(blank=True, db_column='Grado', max_length=255, null=True)),
                ('esc', models.CharField(blank=True, db_column='Esc', max_length=255, null=True)),
                ('puesto_ptal', models.CharField(blank=True, db_column='Puesto Ptal', max_length=255, null=True)),
                ('partida_ptal', models.CharField(blank=True, db_column='Partida Ptal', max_length=255, null=True)),
                ('gp_pago', models.CharField(blank=True, db_column='Gp Pago', max_length=255, null=True)),
                ('prog_beneficios', models.CharField(blank=True, db_column='Prog Beneficios', max_length=255, null=True)),
                ('fh_ult_actz', models.CharField(blank=True, db_column='F/H Últ Actz', max_length=255, null=True)),
                ('por', models.CharField(blank=True, db_column='Por', max_length=255, null=True)),
                ('hr_estd_semn', models.CharField(blank=True, db_column='Hr Estd/Semn', max_length=255, null=True)),
                ('descr', models.CharField(blank=True, db_column='Descr', max_length=255, null=True)),
                ('gp_trabajo', models.CharField(blank=True, db_column='Gp Trabajo', max_length=255, null=True)),
                ('org_code', models.CharField(blank=True, db_column='Org Code', max_length=255, null=True)),
                ('grupo_cd_sal', models.CharField(blank=True, db_column='Grupo Cd Sal', max_length=255, null=True)),
                ('formal_desc', models.CharField(blank=True, db_column='FormalDesc', max_length=255, null=True)),
                ('pto_compt', models.CharField(blank=True, db_column='Pto Compt', max_length=255, null=True)),
                ('posn_clv', models.CharField(blank=True, db_column='Posn Clv', max_length=255, null=True)),
                ('presupuesto', models.CharField(blank=True, db_column='Presupuesto', max_length=255, null=True)),
                ('nombre_puesto', models.CharField(blank=True, db_column='Nombre Puesto', max_length=255, null=True)),
            ],
            options={
                'db_table': 'MOV_POS',
                'managed': True,
            },
        ),
    ]
