# Generated by Django 6.0.4 on 2026-05-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0003_movpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPtoFunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_pto_funcional', models.CharField(blank=True, db_column='Cd Pto Funcional', max_length=255, null=True)),
                ('nombre_puesto_funcional', models.CharField(blank=True, db_column='Nombre Puesto Funcional', max_length=255, null=True)),
                ('cd_norm', models.CharField(blank=True, db_column='CdNorm', max_length=255, null=True)),
            ],
            options={
                'db_table': 'CAT_PTO_FUNC',
                'managed': True,
            },
        ),
    ]
