# Generated by Django 6.0.4 on 2026-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0005_bajassighistorico_empleadoscompletossighistorico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zafirobitacora',
            name='logs_en_vivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
