# Generated by Django 6.0.4 on 2026-05-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0006_zafirobitacora_logs_en_vivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoscompletossig',
            name='posicion',
            field=models.CharField(blank=True, db_column='Posición', db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoscompletossighistorico',
            name='posicion',
            field=models.CharField(blank=True, db_column='Posición', db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='movpos',
            name='estado_psn',
            field=models.CharField(blank=True, db_column='Estado Psn', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movpos',
            name='no_pos_actual',
            field=models.CharField(blank=True, db_column='Nº Pos Actual', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movposhistorico',
            name='estado_psn',
            field=models.CharField(blank=True, db_column='Estado Psn', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movposhistorico',
            name='no_pos_actual',
            field=models.CharField(blank=True, db_column='Nº Pos Actual', db_index=True, max_length=255, null=True),
        ),
    ]
