# Generated by Django 6.0.4 on 2026-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0008_bajassigstaging_empleadoscompletossigstaging_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla1800plazas',
            name='cdgo_pto_fun_r',
        ),
        migrations.RemoveField(
            model_name='plantilla1800plazas',
            name='nombre_puesto_funcional_escenario',
        ),
        migrations.RemoveField(
            model_name='plantilla1800plazas',
            name='posición_civil_sedena_semar',
        ),
        migrations.RemoveField(
            model_name='plantilla1800plazas',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='plantilla1800plazas',
            name='puesto_registrado',
        ),
        migrations.RemoveField(
            model_name='plantilla1800plazas',
            name='riuf_escenario',
        ),
        migrations.AddField(
            model_name='plantilla1800plazas',
            name='estado_posición',
            field=models.CharField(blank=True, db_column='Estado posición', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plantilla1800plazas',
            name='ipe',
            field=models.CharField(blank=True, db_column='IPE', max_length=255, null=True),
        ),
    ]
