# Generated by Django 6.0.4 on 2026-05-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscenarioPresupuestal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ejercicio', models.IntegerField(default=2025)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabuladorPecen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nivel', models.CharField(max_length=10, verbose_name='Nivel')),
                ('zona', models.CharField(max_length=2, verbose_name='Zona')),
                ('denominacion', models.CharField(max_length=255, verbose_name='Denominación')),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('compensacion_garantizada', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('despensa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prevision_social', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ayuda_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capacitacion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Tabulador PECEN',
                'verbose_name_plural': 'Tabuladores PECEN',
            },
        ),
        migrations.CreateModel(
            name='ValuacionPresupuestariaPorNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(db_column='NIVEL', max_length=255)),
                ('zona', models.CharField(db_column='ZONA', max_length=255)),
                ('codigo', models.CharField(db_column='CODIGO', max_length=255)),
                ('puesto_o_categoria', models.CharField(db_column='PUESTO_O_CATEGORIA', max_length=255)),
                ('sueldo', models.CharField(db_column='SUELDO', max_length=255)),
                ('compensacion_garantizada', models.CharField(db_column='COMPENSACION_GARANTIZADA', max_length=255)),
            ],
            options={
                'db_table': 'valuacion_presupuestaria_por_nivel',
            },
        ),
        migrations.CreateModel(
            name='PlazaPresupuestada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazas', to='presupuesto.escenariopresupuestal')),
                ('tabulador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.tabuladorpecen')),
            ],
        ),
    ]
