# Generated by Django 6.0.4 on 2026-05-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_alter_tabuladorpecen_nivel_alter_tabuladorpecen_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plazapresupuestada',
            name='escenario',
        ),
        migrations.RemoveField(
            model_name='plazapresupuestada',
            name='tabulador',
        ),
        migrations.AlterModelOptions(
            name='valuacionpresupuestariapornivel',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='EscenarioPresupuestal',
        ),
        migrations.DeleteModel(
            name='PlazaPresupuestada',
        ),
        migrations.DeleteModel(
            name='TabuladorPecen',
        ),
    ]
