# Generated by Django 6.0.4 on 2026-05-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_remove_plazapresupuestada_escenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPlazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=20)),
                ('nivel_cruce', models.CharField(max_length=20)),
                ('denominacion', models.CharField(max_length=255)),
                ('zona', models.IntegerField()),
                ('sueldo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('despensa', models.DecimalField(decimal_places=4, max_digits=14)),
                ('prev_social_multiple', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ayuda_servicios', models.DecimalField(decimal_places=4, max_digits=14)),
                ('apoyo_capacitacion', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ayuda_transporte', models.DecimalField(decimal_places=4, max_digits=14)),
                ('compensacion_garantizada', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cuota_issste', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cuota_fovissste', models.DecimalField(decimal_places=4, max_digits=14)),
                ('cuota_cesantia', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ahorro_solidario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('epr_quincenal', models.DecimalField(decimal_places=4, max_digits=14)),
                ('grupo_vacaciones', models.IntegerField()),
                ('grupo_gratificacion', models.IntegerField()),
                ('tiene_epr', models.IntegerField()),
            ],
            options={
                'db_table': 'catalogo_plazas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptosPresupuestal',
            fields=[
                ('concepto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=9)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'conceptos_presupuestal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConstantesSistema',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'constantes_sistema',
                'managed': False,
            },
        ),
    ]
