# Generated by Django 6.0.4 on 2026-05-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScgCatDeterminantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(blank=True, max_length=255, null=True)),
                ('unidaddenegocio', models.CharField(blank=True, db_column='unidadDeNegocio', max_length=255, null=True)),
                ('unidadadministrativa', models.CharField(blank=True, db_column='unidadAdministrativa', max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('determinante', models.CharField(blank=True, max_length=255, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_determinantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatDeterminantesCopia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(blank=True, max_length=255, null=True)),
                ('unidaddenegocio', models.CharField(blank=True, db_column='unidadDeNegocio', max_length=255, null=True)),
                ('unidadadministrativa', models.CharField(blank=True, db_column='unidadAdministrativa', max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('determinante', models.CharField(blank=True, max_length=255, null=True)),
                ('dependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('activo_2', models.IntegerField()),
            ],
            options={
                'db_table': 'scg_cat_determinantes_copia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatInstruccion',
            fields=[
                ('idinstruccion', models.AutoField(db_column='idInstruccion', primary_key=True, serialize=False)),
                ('instruccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_instruccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatMedioRecepcion',
            fields=[
                ('idmediorecepcion', models.IntegerField(db_column='idMedioRecepcion', primary_key=True, serialize=False)),
                ('mediorecepcion', models.CharField(blank=True, db_column='medioRecepcion', max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_medio_recepcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatPrioridad',
            fields=[
                ('idprioridad', models.AutoField(db_column='idPrioridad', primary_key=True, serialize=False)),
                ('prioridad', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_prioridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatStatusAsunto',
            fields=[
                ('idstatusasunto', models.AutoField(db_column='idStatusAsunto', primary_key=True, serialize=False)),
                ('statusasunto', models.CharField(blank=True, db_column='statusAsunto', max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_status_asunto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatStatusResponse',
            fields=[
                ('idstatusresponse', models.AutoField(db_column='idStatusResponse', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'scg_cat_status_response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatStatusTurnado',
            fields=[
                ('idstatusturnado', models.AutoField(db_column='idStatusTurnado', primary_key=True, serialize=False)),
                ('statusturnado', models.CharField(blank=True, db_column='statusTurnado', max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_status_turnado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatTema',
            fields=[
                ('idtema', models.AutoField(db_column='idTema', primary_key=True, serialize=False)),
                ('tema', models.CharField(blank=True, max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_tema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatTipoDocumento',
            fields=[
                ('idtipodocumento', models.AutoField(db_column='idTipoDocumento', primary_key=True, serialize=False)),
                ('tipodocumento', models.CharField(db_column='tipoDocumento', max_length=255)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_tipo_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatUnidadAdministrativa',
            fields=[
                ('idunidadadministrativa', models.AutoField(db_column='idUnidadAdministrativa', primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=10, null=True)),
                ('unidadadministrativa', models.CharField(blank=True, db_column='unidadAdministrativa', max_length=255, null=True)),
                ('esunidadadministrativa', models.IntegerField(blank=True, db_column='esUnidadAdministrativa', null=True)),
                ('esunidaddenegocio', models.IntegerField(blank=True, db_column='esUnidadDeNegocio', null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_unidad_administrativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScgCatUnidadResponsable',
            fields=[
                ('idunidadresponsable', models.AutoField(db_column='idUnidadResponsable', primary_key=True, serialize=False)),
                ('unidadresponsable', models.CharField(blank=True, db_column='unidadResponsable', max_length=255, null=True)),
                ('clave', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('idunidadadministrativa', models.CharField(blank=True, db_column='idUnidadAdministrativa', max_length=15, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='fechaRegistro', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('idusuariomodifica', models.IntegerField(blank=True, db_column='idUsuarioModifica', null=True)),
                ('idusuarioregistra', models.IntegerField(blank=True, db_column='idUsuarioRegistra', null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scg_cat_unidad_responsable',
                'managed': False,
            },
        ),
    ]
