# Generated by Django 6.0.4 on 2026-05-18 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoAsunto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionAsuntoConTipoOficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idAsuntoSCG', models.IntegerField(blank=True, null=True)),
                ('idTipoAsunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat_tipo_oficio.cattipoasunto')),
            ],
        ),
    ]
