# Generated by Django 6.0.4 on 2026-05-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_tipo_oficio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsuntoValuacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idAsuntoSCG', models.IntegerField(blank=True, null=True)),
                ('valuacion', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Procedente', 'Procedente'), ('Improcedente', 'Improcedente'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50, null=True)),
            ],
        ),
    ]
