# Generated by Django 6.0.4 on 2026-05-19 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_tipo_oficio', '0002_asuntovaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuntovaluacion',
            name='oficio_resolucion',
            field=models.FileField(blank=True, null=True, upload_to='oficios/valuacion/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Oficio de Resolución (PDF)'),
        ),
    ]
